name = "emby-proxy"
main = "worker.js"
compatibility_date = "2025-05-15"

[vars]
BASE_DOMAIN = "example.com"
ADMIN_TOKEN = "liu1752256014"
CF_API_TOKEN = ""
CF_ZONE_ID = ""
CF_ACCOUNT_ID = ""
DNS_RECORD_NAME = "emby"

[[d1_databases]]
binding = "DB"
database_name = "emby-proxy-db"
database_id = "9687f3e5-6fbe-46c1-8d79-8602088b648b"
